# Generated by Django 5.1.7 on 2025-03-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('operating_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_type', models.CharField(choices=[('General', 'General'), ('Specialty', 'Specialty'), ('Teaching', 'Teaching'), ('Private', 'Private'), ('Public', 'Public')], max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('establishment_date', models.DateField()),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('accreditation_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('accrediting_body', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_services', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('operating_hours', models.CharField(max_length=100)),
                ('telemedicine', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('owner_name', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=100)),
                ('funding_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Non-Profit', 'Non-Profit')], max_length=50)),
                ('license_number', models.CharField(max_length=100)),
            ],
        ),
    ]
