# Generated by Django 5.1.7 on 2025-03-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='interns',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='hospital.intern'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='hospital.patient'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='interns',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='hospital.intern'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='hospital.patient'),
        ),
        migrations.CreateModel(
            name='MaternalMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_rate', models.CharField(max_length=20)),
                ('fetal_heart_rate', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=10)),
                ('monitoring_date', models.DateField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternal_monitoring', to='hospital.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternal_monitoring', to='hospital.patient')),
            ],
        ),
    ]
